### ISSUE TITLE
support get,set with current env

### ISSUE THREAD

**Issue by o-** [reactorlabs/rir#1009]
Calls to get/set without env should be constantfolded to StVar/LdVar. Actually knucleotide does that...

**Comment by hugomg** [comment]
If I understand the knucleotide code correctly, the environments are used as hash tables and the keys are not constant. It doesn't seem that this optimization would help. I feel that this implementing this might not be worth it. Of course, we can  reconsider if we come across a different benchmark that would benefit from this.
