### ISSUE TITLE
Unstable (and non-deterministic?) type for compiled function

### ISSUE THREAD

**Issue by vogr** [reactorlabs/rir#1056]
I have encountered a surprising behavior with the following code:

```
f <- function(x) NROW(x)
a <- c(1,2,3,4)

typeof(f(a))
typeof(f(a))
typeof(f(a))
typeof(f(a))
typeof(f(a))
typeof(f(a))
```

With master compiled as release (and with `PIR_DEBUG=ShowWarnings`), sometimes I get this output:

```
> f <- function(x) NROW(x)
> a <- c(1,2,3,4)
> 
> typeof(f(a))
[1] "integer"
> typeof(f(a))
[1] "integer"
> typeof(f(a))
[1] "integer"
> typeof(f(a))

╞═══════════════════════════════╡  Compiling f  ╞══════════════════════════════╡
[1] "integer"
> typeof(f(a))
[1] "integer"
> typeof(f(a))
[1] "integer"
```

and sometimes I get this different output (!):

```
> f <- function(x) NROW(x)
> a <- c(1,2,3,4)
> 
> typeof(f(a))
[1] "integer"
> typeof(f(a))
[1] "integer"
> typeof(f(a))
[1] "integer"
> typeof(f(a))

╞═══════════════════════════════╡  Compiling f  ╞══════════════════════════════╡
[1] "double"
> typeof(f(a))

╞═════════════════════════════╡  Compiling NROW  ╞═════════════════════════════╡
[1] "integer"
> typeof(f(a))

╞═══════════════════════════════╡  Compiling f  ╞══════════════════════════════╡
[1] "integer"
```

In particular, note that the type for the 4th call is "double" instead of "integer".

(Note: this behaviour breaks the `summary` function on data.frames after PR https://github.com/reactorlabs/rir/pull/1050.  This happens because the method `summary.data.frame` calls `vapply` with a function similar to `FUN <- function(x) NROW(x)`. The 4th call to FUN fails with `values must be type 'integer',  but FUN(X[[3]]) result is type 'double'`)

**Comment by o-** [comment]
interesting :)

If I run it with PIR_DEBUG_DEOPTS=1 then in the case where you see "double" I get:

```
DEOPT, assumption 
real⁻         %9.1  = CastType           d     dn %7.0
(int|real)$⁻<int$⁻> %9.2  = CallSafeBuiltin    vwed  length(%9.1) 
val⁻<nil⁻>  %19.0 = CastType           d     dn %17.5
int$#⁻        %15.0 = LdConst                  1
val?            %15.1 = Extract1_1D        wed   %19.0, %15.0, elided
val?<int$⁻>   %12.0 = Phi                      %9.2:BB11, %15.1:BB15
lgl$#⁻        %12.1 = IsType                   %12.0 isA int$⁻
```

So that explains the subsequent compilation, because the deoptimized code is retired.

And it also shows that the double comes either from `Extract1_1D` or `lenght(...)`. My bet is on the former...

**Comment by o-** [comment]
aha, got it:

**Comment by o-** [comment]
So, we have this famous and always broken optimization that tries to store values of type (int|double) in a double, if none of it's uses distinguish the two... And, well it was still broken... PR follows
