### ISSUE TITLE
PIR Speculative Optimizations

### ISSUE THREAD

**Issue by charig** [reactorlabs/rir#127]
* Inline caching?
* Type specializations

**Comment by o-** [comment]
I discussed some of this with @janvitek a while ago. One of the conclusions was, that we can have speculative optimizations without deopt, by encoding the speculation in the signature and keeping some dynamic context of true assumptions.

A stupid example: we could have a bit in the signature that says: "plus is plus", then we can have a function version that has this bit set. Then, if you call a function and currently you know that "plus is plus", this means your incoming assumption context has the "plus is plus" bit set. So the two contexts match up and you are allowed to pick the version.

**Comment by o-** [comment]
we have a proposal https://www.o1o.ch/lab/entry/46361g4zp9nveus4tl9vpzobk2rlpe7o2fdfdxvlaqi1f5kopcyqpjcftjqboifr.html

**Comment by o-** [comment]
we have an implementation https://github.com/reactorlabs/rir/pull/246
