### ISSUE TITLE
Removal of as-package code

### ISSUE THREAD

**Issue by petamaj** [reactorlabs/rir#13]
Initially we have envisioned `rir` to work in two modes, the latter being as a standalone package to vanilla `gnu-r`. This has soon been abandoned. Check that there are no remnants of this functionality in current code base if there are, delete them.

**Comment by kondziu** [comment]
I found a few things that might also warrant removal in there, I'd like an opinion on that.

Thing 1: `USE_RIR_CONTEXT_SETUP`
It's a define that was only set to true if `RIR_AS_PACKAGE` was off. It's used in a couple of places in `interp.c`, I think when calling external functions. Don't know if that is actually a separate switch used for something else or if it would be always on if `RIR_AS_PACKAGE` is off.

Things 2 and 3: `createWrapperAst` and `createWrapperPromise`
When `RIR_AS_PACKAGE` is turned off these functions just return their argument. It looks like  `createWrapperAst` has a couple of occurances. `createWrapperPromise` doesn't have any that I can see.

**Comment by o-** [comment]
Hi, thanks for looking into this.
1. So this flag is not really related. R internally uses the RCNTXT structs to track call frames. At some point we had an experimental workaround to support creating contexts in RIR. But by now we have made the RCNTXT struct and the required apis public. As you can see for example in https://github.com/reactorlabs/rir/blob/master/rir/src/interpreter/interp.c#L504 we are perfectly capable of creating proper contexts and as you saw USE_RIR_CONTEXT_SETUP is always true. Feel free to remove it in the same go.

2./3. They can both be removed. The Idea there was that we could execute RIR methods even if gnu R does not know our bytecode. The wrappers would be legal R functions which would tail-call a C primitive which would tail-call into our interpreter. :)
