### ISSUE TITLE
Add R API for analysis introspection

### ISSUE THREAD

**Issue by petamaj** [reactorlabs/rir#14]
Add R API to get results of `rir` analyses, i.e. run given analysis on defined code, grab the results from the drivers and print the state in some reasonably meaningful way, all from within R. 

(note this is potentially a big task)

**Comment by aviralg** [comment]
You mean the static analysis framework?

**Comment by o-** [comment]
Yes.

As a first step it would be nice if there is an R api to run certain existing static analysis from https://github.com/reactorlabs/rir/tree/master/rir/src/code on some R code and print the results.

A second step would be to query the results so you can use them in your R code.

Further out one could even think of specifying the analysis in R. But that is far out :)

**Comment by aviralg** [comment]
I see. Since I am going to work on the strictness analysis, I will handle this issue.
