### ISSUE TITLE
update to a recent R release

### ISSUE THREAD

**Issue by o-** [reactorlabs/rir#159]
we are running on an old version. We should port our patches to a current version and update rir.

**Comment by JanJecmen** [comment]
@o- So, the reactorlabs/gnur repo is not a fork of anything, how do you sync it with some recent R? Wanted to have a look at this since the build on mac fails and I believe it was fixed in R 3.4

**Comment by o-** [comment]
it is of https://github.com/wch/r-source

**Comment by JanJecmen** [comment]
Cosed by #193
