### ISSUE TITLE
Building rir options not enabled memory-profiling

### ISSUE THREAD

**Issue by chris-english** [reactorlabs/rir#262]
Hi, 

What is the proper cmake instruction to enable memory-profiling in build. 

Thanks,
Chris

**Comment by mhyee** [comment]
We do not have cmake support for memory profiling. However, you could always modify the [sync.sh](https://github.com/reactorlabs/rir/blob/1a8c1fe05b8445514ae14dc7e092f76ee7bc1fb4/tools/sync.sh#L46L51) file and add `--enable-memory-profiling` to the arguments to `configure`.

What do you want to use RIR for? It's an experimental JIT compiler and a work in progress.

**Comment by chris-english** [comment]
That tells me what to modify, thank you. 

I innocently wanted to compare 'speed ups' as may be found in using various functions in the CRAN tsmp package (stamp, stomp, scrimp, find_motif) for time series analysis. This has lead to/through:

rdyncall to external C code, though I'm still fishing around for the right entry point and getting my struct calls properly structured - no success there yet

Tried to get Duncan Temple Lang's Rllvm to compile to no avail. He argues to not change the R compiler but essentially use IR under the hood. You guys clearly don't worry about changing the R compiler, and since everything (package) I load, loads, as a user I have no complaint.

The matrix profile approach to time series is: https://www.cs.ucr.edu/~eamonn/MatrixProfile.html
where I'm look at the VALMOD approach of Linardi, et al.

To date, building objects or results takes 4 hrs for 262K time series vector in R or C using my old box, though memory handling is of course better in C, hence my interest in enabling memory-profiling under R.  

I find your work very interesting and will continue to explore. Thanks, Chris

**Comment by chris-english** [comment]
That's ~/rir/rir/tools/sync.sh for others interested.
