### ISSUE TITLE
Incorrectly copying the invocationCount

### ISSUE THREAD

**Issue by mhyee** [reactorlabs/rir#263]
When we compile a PIR function back to RIR and create a new entry in the DispatchTable, we copy the old invocation count. We should probably initialize the count to 0.

**Comment by o-** [comment]
no, the invocation count is used to trigger optimization

**Comment by mhyee** [comment]
Ah, I see now. The behaviour is a bit confusing, but it is intentional. Otherwise the optimized function would get optimized again.
