### ISSUE TITLE
source(""loadRjit") : No such file or directory

### ISSUE THREAD

**Issue by chris-english** [reactorlabs/rir#265]
started session with 

> source("loadRjit")
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'loadRjit': No such file or directory

retreating from that and thinking well, perhaps demo:
> getwd()
[1] "/home/chris/rir/rir"
> list.files("demo")
[1] "demo.R"       "demo_rir.R"   "demo_rir.txt"
> source("demo/demo_rir.R")
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'loadRjit': No such file or directory

wondering where I should expect to find loadRjit, 
also don't have rir.print of an rir.compile(d) object
Thanks, Chris

**Comment by mhyee** [comment]
You will want to look at [rir/R/rir.R](https://github.com/reactorlabs/rir/blob/master/rir/R/rir.R) for the current API to the RIR compiler. The most relevant functions will probably be `rir.compile` and `rir.disassemble`.

Example:

```
bash$ bin/R
> # define a simple R function
> f <- function(x,y) x+y
>
> # compile to RIR bytecode and call
> rir.compile(f)
function(x,y) x+y
<bytecode: 0x4554c68>
> f(40, 2)
[1] 42
>
> # print the bytecode
> rir.disassemble(f)
* closure 0x4552968 (vtable 0x4554c98, env 0x26d4c38)
= vtable slot <0> (0x3dd02d8, invoked 1) =
0:
      0   guard_fun_  + == 0x26acab0
     13   ldvar_  x
     18   ldvar_  y
     23   [ double(s) x double(s) ]
     32   ; x + y
          add_
     33   ret_
```
