### ISSUE TITLE
Find a way to lazily create the argslist in doCall

### ISSUE THREAD

**Issue by mhyee** [reactorlabs/rir#298]
On January 15, 2019, @o- wrote:

> I found a todo that could be implemented: https://github.com/reactorlabs/rir/blob/master/rir/src/interpreter/interp.cpp#L655
> 
> this should actually remove quite some overhead
> apparently, when we call a function with all arguments on the stack, we still create an argslist
> just because there could be a function looking at the argslist...
> this is kind of stupid (this is a lot of cons allocations for nothing in most cases)
> so that would be a neat task if somebody looks for a thing to do

**Comment by charig** [comment]
Integrated on PR #305
