### ISSUE TITLE
Keyboard interrupt

### ISSUE THREAD

**Issue by JanJecmen** [reactorlabs/rir#32]
The following code is not interruptible because RIR doesn't check for SIGINT
```
> f <- function() repeat NULL
> f()
^C
```
(GNUR's `bcEval` uses `BC_CHECK_SIGINT` in some of its instructions which goes to `R_CheckUserInterrupt` in a similar way that the AST interpreter does it)

**Comment by mhyee** [comment]
For reference, here is the GNU R repo we use: https://github.com/reactorlabs/gnur

And [here is where bcEval is defined](https://github.com/reactorlabs/gnur/blob/00bbf1eb95edca8846dcd5e3c65e29d387433f1a/src/main/eval.c#L6227).

**Comment by mhyee** [comment]
Fixed by #398.
