### ISSUE TITLE
GraphViz output for PIR

### ISSUE THREAD

**Issue by mhyee** [reactorlabs/rir#324]
Suggested by @o-.

Add some debug flag to print the PIR CFG in [GraphViz format](https://graphviz.org/documentation/).

Doesn't have to be fancy. As a first implementation, try::

```c++
// Give it the entry BB of the function
void printDot(BB* bb) {
    std::cout << "digraph G" << " {\n";
    Visitor::run(bb, [](BB* bb) {
        if (bb->next0)
            std::cout << bb->id << "->" << bb->next0->id << ";\n";
        if (bb->next1)
            std::cout << bb->id << "->" << bb->next1->id << ";\n";
    });
    std::cout << "}\n";
}

```

Fancier version: include the instructions in the basic blocks. [TAJS](https://github.com/cs-au-dk/TAJS/) had GraphViz output with instructions and it was pretty readable.

**Comment by o-** [comment]
@mhyee ah now I get what you mean. That would be even more awesome! I did some manual experiments. I turned this:

```
BB0
  val?^   %0.0  = LdArg            0
  env     e0.1  = MkEnv            a=%0.0, parent=<environment: R_GlobalEnv>
  val?    %0.2  = Force!           %0.0, e0.1
  t       %0.3  = AsTest           %0.2
  void            Branch           %0.3 -> BB2 (if true) | BB1 (if false)
BB2
  real$'  %2.0  = LdConst          [1] 2 
  goto BB3
BB1
  real$'  %1.0  = LdConst          [1] 3 
  goto BB3
BB3
  real$'  %3.0  = Phi              %1.0:BB1, %2.0:BB2
  void            Return           %3.0
```

into:

```
digraph {

  BB0 [shape="box", fontname="monospace", label="\
val?^   %0.0  = LdArg            0 \l\
env     e0.1  = MkEnv            a=%0.0, parent=<environment: R_GlobalEnv> \l\
val?    %0.2  = Force!           %0.0, e0.1 \l\
t       %0.3  = AsTest           %0.2 \l\
void            Branch           %0.3 \l"];
  BB0 -> BB2;
  BB0 -> BB1;

  BB2 [shape="box", fontname="monospace", label="\
real$'  %2.0  = LdConst          [1] 2 \l"];
  BB2 -> BB3;

  BB1 [shape="box", fontname="monospace", label="\
real$'  %1.0  = LdConst          [1] 3 \l"];
  BB1 -> BB3;

  BB3 [shape="box", fontname="monospace", label="\
real$'  %3.0  = Phi              %1.0:BB1, %2.0:BB2 \l\
void            Return           %3.0 \l"];

}
```

which creates:

![cfg](https://o1o.ch/scratch/cfg.jpg)


Overall, I think a great Idea! But I think the dot is noisy enough, that I would like to keep both -- the textual output and the dot output. Otherwise both of them will be a bad compromise.

**Comment by o-** [comment]
But just the BB nr graph would be useful too, and especially for large graphs potentially even better than this. So I would probably focus on getting just the node number graph.

**Comment by JanJecmen** [comment]
why not have all? textual, just numbers, numbers and instructions :)

**Comment by charig** [comment]
We should look for an application that accepts graphviz format over a network port and creates the graphs on the fly

**Comment by o-** [comment]
> We should look for an application that accepts graphviz format over a network port and creates the graphs on the fly

that application is called bash

`while true; do nc -l 8000 | dot -Tjpg | display - &; done`
