### ISSUE TITLE
runBenchs.sh should not return 0 if a benchmark crashes

### ISSUE THREAD

**Issue by o-** [reactorlabs/rir#346]
the `tools/runBenchs.sh` script which we use in ci does not return a non zero exit status if a test crashes. thus the CI jobs pass, even if the bm crash

**Comment by o-** [comment]
sorry, I think I was wrong here, need to investigate more and will close it if it's not true

**Comment by charig** [comment]
Let me know if I can help, but I remembered testing this and my recollection is that `rebench` returns 0 only when all the benchmarks ran ok.
