### ISSUE TITLE
Improved BBTransform

### ISSUE THREAD

**Issue by mhyee** [reactorlabs/rir#395]
It feels like we're doing a lot of ad-hoc transformations that involve adding or removing basic blocks.

It would be nice to have some general API for inserting or removing basic blocks.

This is complicated by issues like phi placement (adding, removing, or splitting phis, and then updating all usages of an instruction argument). There is also a constraint that a basic block containing a deopt _must_ be immediately preceded by a basic block with a checkpoint---even an empty basic block in between is forbidden. There may be other constraints like this.

Related to this (but may need to be fixed at the same time) is that we compute the CFG (and other related structures, like the dominance graph, dominance frontier, liveness analysis, etc.), but then any change to the basic blocks invalidates these data. So either we should build the CFG into the basic block structure, or have some way of updating the CFG when we add/remove basic blocks.

**Comment by o-** [comment]
done
