### ISSUE TITLE
RIR 2 PIR ungracefull crash 

### ISSUE THREAD

**Issue by charig** [reactorlabs/rir#488]
When compiling RIR to PIR, in case the compiler fails when computing the `mergepoints`, the compiler end up in a kind of infinite loop and consumes huges amounts of memory finally crashing.

It would be great if the compilary failed gracefully instead.

To repro just run: `tools:::.check_code_usage_in_package(package = "compiler")`.

To ensure there is a missing mergepoint under that code just remove the condition: `std::get<0>(m) == first ||` in `findMergepoints` (rir_2_pir.cpp).

See #477.

**Comment by o-** [comment]
can't reproduce anymore
