### ISSUE TITLE
Assertions

### ISSUE THREAD

**Issue by Jakobeha** [reactorlabs/rir#605]
Here are some potential assertions we could implement:

- **Manual type assertions**
  - Syntax: `rir.assert(x, type="int")`
  - Semantics: Fails if the value isn't the given PIR type
  - Optimization: Afterward, PIR can assume that the value is the given type
- **Function signatures**
  - Syntax: `rir.addProperty(f, sig="val int$ -> int")`. Also we could record functions input / return types, and automatically add the function signatures if RIR is run with some flag
  - Semantics: Changes the function so it asserts its inputs are the correct types, runs the body of the inner function, and asserts its output is the correct type
  - Optimization: If we statically resolve the function, instead of emitting a `static_call_` we emit a `static_call_special_`, which checks the input types and return types at the callsite, skips checking arguments when PIR statically resolves they are of the correct type, and skips checking the return type when PIR statically resolves (inside the closure) it's the correct type. Also, PIR can use the this closure's return type
- **Strictness**
  - Syntax: `rir.addProperty(f, Strict)` modifies `f` in-place
  - Semantics: Changes the function so it forces all arguments in sequential order, then runs the body of the inner function with those arguments
  - Optimization: If we statically resolve the function, instead of emitting a `static_call_` we can emit a `static_call_special_`, which forces the arguments at the callsite, and passes them directly. It also doesn't need to build promises for already forced arguments
- **No environment**
  - Syntax: `rir.addProperty(f, NoReflection)` modifies `f` in-place. Also we could record functions which don't use their environment, then automatically add the assertions if RIR is run with some flag
  - Semantics: Assert that a function doesn't use reflection (including any promises forced in the body). It can probably be implemented by adding checks to `get_env_` and other instructions, so that if the calling closure has the `NoReflection` property they will fail
  - Optimization: In PIR the variables can be replaced with stack values

**Comment by o-** [comment]
closing this for now, as we are moving towards integrating this into contexts
