### ISSUE TITLE
Investigating loop peeling and benchmarks

### ISSUE THREAD

**Issue by mhyee** [reactorlabs/rir#629]
Loop peeling doesn't seem to help as much as we'd like, and we're not sure why.

I plan to inspect the PIR output, with and without loop peeling, for the [areWeFast](https://github.com/reactorlabs/RBenchmarking/tree/master/Benchmarks/areWeFast) and [shootout](https://github.com/reactorlabs/RBenchmarking/tree/master/Benchmarks/shootout) benchmarks. I want to figure out what's happening, why loop peeling isn't helping, and what sort of optimizations _could_ help.

I'll make a new comment for each benchmark, and link to them from here.

  - [x] [areWeFast] [bounce](https://github.com/reactorlabs/rir/issues/629#issuecomment-525461498)
  - [ ] [areWeFast] mandelbrot
  - [x] [areWeFast] [storage](https://github.com/reactorlabs/rir/issues/629#issuecomment-524996567)
  - [ ] [shootout] binarytrees
  - [ ] [shootout] fannkuch
  - [ ] [shootout] fasta
  - [ ] [shootout] fastaredux
  - [ ] [shootout] knucleotide
  - [ ] [shootout] mandelbrot
  - [ ] [shootout] nbody
  - [ ] [shootout] pidigits
  - [ ] [shootout] regexdna
  - [ ] [shootout] reversecomplement
  - [ ] [shootout] spectralnorm

**Comment by mhyee** [comment]
## [areWeFast] storage

**Update on Sept 6 2019:** I ran this on 23704e021bcc0426ebcac7327caa6a78a30e222d. See bottom of this comment for updates.

---

I ran this on 7fb180561e291269d84e5de8f6bd1bb67ad75f82. I used an "inlined" version of [`storage.r`](https://github.com/reactorlabs/RBenchmarking/blob/46448fe7e3f0ad32f7dd5f1371ad13aaf4b74d0f/Benchmarks/areWeFast/storage.r) so that it was a single, self-contained script that took no arguments. The function in question with the loop is `buildTreeDepth`, so I excluded output for all other functions.


The [attached archive (storage.zip)](https://github.com/reactorlabs/rir/files/3542602/storage.zip) includes the version of `storage.r` I used, a file with the git commit, and two directories: `peeling-off` and `peeling-on`. Inside each of those directories is the RIR output, PIR output, GraphViz output, and PDFs of the control-flow graph for each function version.

### Observations

#### peeling-off

There are four versions here.

1a. The ["base case"](https://github.com/reactorlabs/RBenchmarking/blob/46448fe7e3f0ad32f7dd5f1371ad13aaf4b74d0f/Benchmarks/areWeFast/storage.r#L18) is compiled to an unconditional deopt, because it contains a call to `c`, and we don't want a call (that is never taken, up to this point) to taint the abstract state.

Versions 2a through 4a are almost identical. I suspect there's a deopt loop here.

2a. The unconditional deopt from 1a is taken, so the branch is restored. Also, for some reason, `%4.9` is forced twice, and the result of the first force (`%4.10`) is never used.

![image](https://user-images.githubusercontent.com/547059/63715522-ee541d80-c811-11e9-97f2-6e24a4a52ac5.png)

3a. BB10, the bulk of the loop body, is shortened. This corresponds to [this bit of R](https://github.com/reactorlabs/RBenchmarking/blob/46448fe7e3f0ad32f7dd5f1371ad13aaf4b74d0f/Benchmarks/areWeFast/storage.r#L23). The result of the `StaticCall` gets some type feedback, and a pair of `LdVar`/`Force` instructions (for the arguments `array` and `i`) get removed.

4a. This version looks almost the same as 2a, except that there is a bit of type feedback in BB12 and BB10.

Note that 2a recursively calls itself, 3a calls 4a, and 4a recursively calls itself.

Compare 2a, 3a, and 4a:
![image](https://user-images.githubusercontent.com/547059/63715828-a1bd1200-c812-11e9-85c9-2bc787142c59.png)
![image](https://user-images.githubusercontent.com/547059/63715909-c5805800-c812-11e9-91d6-a435dff18c66.png)
![image](https://user-images.githubusercontent.com/547059/63716027-0bd5b700-c813-11e9-811a-98c4850dedde.png)

#### peeling-on

This time, there are six versions, and the story is very similar to having loop peeling disabled. Even looking at BB10 from above, the main body of the loop, there isn't very much that looks like loop peeling could help.

1b. Like in 1a, the base case with call to `c` gets compiled as an unconditional deopt. But so does the main loop body.

2b. Both deopts get hit, so both branches are restored. Loop peeling works as expected; I see two copies of the loop body (BB8 and BB11). There's also some type feedback this time.

3b. Similar story to 3a, a pair of `LdVar`/`Force` instructions get removed. This time it's removed from both copies of the loop body.

4b. Identical to 2b.

5b. Identical to 3b.

6b. Identical to 4b.

Note that 1b recursively calls itself, 2b recursively calls itself, 3b calls 4b, 4b recursively calls itself, 5b calls 6b, and 6b recursively calls itself.

### Action items

It looks like this is a benchmark where there's nothing that benefits from loop peeling. However, there's still a few things to look at.

1. The unconditional deopts seem a bit aggressive, and could cause a performance hit if we keep deopting. Maybe we could be less aggressive? But then an unknown call might taint the abstract state.

2. ~Why is there a deopt loop? Without loop peeling, we got 2a -> 3a -> 2a'. With loop peeling, we get 2b -> 3b -> 2b -> 3b -> 2b.~

3. Can we do anything about the `LdVar`/`Force` for the function arguments? It seems _something_ is being done, but then it gets undone, and we get the deopt loop.

4. In BB4, we're forcing the same thing twice. I think it's because a promise gets inlined...

5. There's a `LdConst`/`LdVar` for the `buildTreeDepth` that should be optimized in the loop body. I believe #625 should address this.

6. There's a `StVar i` to update the loop counter, but there is no `LdVar i`. We still need to update `i` in case we deopt, but in that case, we should be able to push the `StVar i` into the deopt block. In fact, it would be nice to push the `MkEnv` into the deopt block, but I'm guessing we can't do it because of all the forces and things that could mess with the environment...

---

**Update on Sept 6 2019 for 23704e021bcc0426ebcac7327caa6a78a30e222d.**

No significant changes for peeling-off or peeling-on. Maybe some of the BBs got compiled slightly differently, but I'm seeing some of the same issues as before. Nothing in the recent commits seems to have helped.

However, I did find another clue about the "deopt loop," but it might need more investigation.

There was a loop where 2 -> 3 -> 4 -> 5 -> 6 and 2 = 4 = 6 and 3 = 5.

What seems to be happening is that:

- 2 recursively calls itself
- 3 calls 4 and 4 recursively calls itself
- 5 calls 6 and 6 recursively calls itself

Furthermore:
- 2, 4, and 6 have the same assumptions (`!ExpMi,CorrOrd,!TMany`)
- 3 and 5 have different assumptions (`Eager0,!Obj0,SimpleReal0,!ExpMi,CorrOrd,!TMany` and `Eager0,!ExpMi,CorrOrd,!TMany` respectively)




[(Back to top)](https://github.com/reactorlabs/rir/issues/629#issue-485383609)

**Comment by mhyee** [comment]
## [areWeFast] bounce

I ran this on 7fb180561e291269d84e5de8f6bd1bb67ad75f82. I used an "inlined" version of [`bounce.r`](https://github.com/reactorlabs/RBenchmarking/blob/46448fe7e3f0ad32f7dd5f1371ad13aaf4b74d0f/Benchmarks/areWeFast/bounce.r) so that it was a single, self-contained script that took no arguments.

Only the [`execute`](https://github.com/reactorlabs/RBenchmarking/blob/46448fe7e3f0ad32f7dd5f1371ad13aaf4b74d0f/Benchmarks/areWeFast/bounce.r#L3L23) function has loops, but there is enough code in [`bounce`](https://github.com/reactorlabs/RBenchmarking/blob/46448fe7e3f0ad32f7dd5f1371ad13aaf4b74d0f/Benchmarks/areWeFast/bounce.r#L29L58) and [`ball`](https://github.com/reactorlabs/RBenchmarking/blob/46448fe7e3f0ad32f7dd5f1371ad13aaf4b74d0f/Benchmarks/areWeFast/bounce.r#L15L19) (closure inside `execute`) that I also looked at them.

The [attached archive (bounce.zip)](https://github.com/reactorlabs/rir/files/3547899/bounce.zip) includes the version of `bounce.r` I used, a file with the git commit, the GraphViz output for `bounce` and `ball`, and two directories: `peeling-off` and `peeling-on`. Inside each of those directories is the RIR output, PIR output, GraphViz output, and PDFs of the control-flow graph for each function version of `execute`.

### Observations

#### ball

Not affected by loop peeling.

There's a sequence of instructions `StVar results; LdVar results; Force`, and it seems like the `LdVar`/`Force` can be removed. I don't think `StVar` can be removed, because there's a `LdVar` later on, and the instructions in between probably taint the environment.

![image](https://user-images.githubusercontent.com/547059/63802720-38580480-c8e1-11e9-8b08-da9a0e7ba0af.png)

#### bounce

Not affected by loop peeling. But there's a lot of deopts happening and some kind of deopt loop in the first half of the program.

There are six versions.

1. There are four `if` expressions, and two of them are compiled as unconditional deopts: [`ball['x'] > xLimit`](https://github.com/reactorlabs/RBenchmarking/blob/46448fe7e3f0ad32f7dd5f1371ad13aaf4b74d0f/Benchmarks/areWeFast/bounce.r#L38L40) and [`ball['y'] < 0`](https://github.com/reactorlabs/RBenchmarking/blob/46448fe7e3f0ad32f7dd5f1371ad13aaf4b74d0f/Benchmarks/areWeFast/bounce.r#L53L55). Maybe these weren't reached the first time `bounce` was executed?

2. The first half of the program changes slightly; it's hard to describe. Look at BB0-BB3 in version 1, and BB0-BB4 in version 2, which correspond to the [first few lines of bounce](https://github.com/reactorlabs/RBenchmarking/blob/46448fe7e3f0ad32f7dd5f1371ad13aaf4b74d0f/Benchmarks/areWeFast/bounce.r#L30L35).

3. The first half of the program reverts to version 1. The unconditional deopt for `ball['y'] < 0` gets executed and the branch is restored. As a result, a promise gets inlined, and we see a double force in BB25.

4. Same as version 3, except that the other unconditional dept (`ball['x'] > xLimit`) gets executed and the branch is restored. This time, promises in two BBs (BB7 and BB22) get inlined, so we see double forces. The entire promise code can also be deleted.

5. The first half of the program reverts to version 2. The rest is the same as version 4.

6. The entire program reverts to version 4.

#### execute (peeling-off)

There are two loops. The body of the [first loop](https://github.com/reactorlabs/RBenchmarking/blob/46448fe7e3f0ad32f7dd5f1371ad13aaf4b74d0f/Benchmarks/areWeFast/bounce.r#L9L13) is pretty long, and we see some promises have been inlined. There's also a lot of `LdFun`s and `Force`s, and it'd be nice to get rid of some of those.

![image](https://user-images.githubusercontent.com/547059/63803680-7a824580-c8e3-11e9-9840-5bc497b82b5d.png)

There isn't anything interesting in the [second loop](https://github.com/reactorlabs/RBenchmarking/blob/46448fe7e3f0ad32f7dd5f1371ad13aaf4b74d0f/Benchmarks/areWeFast/bounce.r#L21).

#### execute (peeling-on)

The changes to the first loop are very minor. There's a `MkEnv` and `MkFunCls` that gets pushed from the preheader into the loop peel -- either way, it's still before the loop body. And a bunch of `LdConst`s get removed from the loop body.

No changes to the second loop.

### Action items

Again, there doesn't seem to be much that can benefit from loop peeling, in this benchmark.

A number of issues are shared with the `storage` benchmark:

1. Unconditional deopts might be too aggressive.

2. There seems to be a deopt loop.

3. It would be nice to get rid of a `LdVar`/`Force` if we just did a `StVar`.

4. Double force occurs whenever we inline a promise.

5. `LdFun` happens repeatedly inside the body of the loop.

[(Back to top)](https://github.com/reactorlabs/rir/issues/629#issue-485383609)

**Comment by o-** [comment]
@mhyee hmm, should I close this for now? or would you like to create more actionable small issues from it?

**Comment by mhyee** [comment]
Yeah, I think we can just close this for now.

Digging this deep into the PIR is time consuming, and for the two I did, I didn't find anything conclusive... just a bunch of really small things which might not even apply now.
